name: copy_with_extension_gen
version: 5.0.2
description: Automatically generating `copyWith` extensions code for classes with `@CopyWith()` annotation.
repository: https://github.com/numen31337/copy_with_extension
homepage: https://github.com/numen31337/copy_with_extension/tree/master/copy_with_extension_gen
issue_tracker: https://github.com/numen31337/copy_with_extension/issues

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=5.13.0"
  build: ^2.4.0
  source_gen: ^1.3.2
  copy_with_extension:
    git:
      url: https://github.com/rasitayaz/dart-copy-with-extension
      ref: dev
      path: copy_with_extension
  meta: ^1.9.1

dev_dependencies:
  equatable: ^2.0.5
  flutter_lints: ^2.0.1
  build_runner: ">=2.4.5"
  test: ^1.24.3
  source_gen_test: ^1.0.5
